### ISSUE TITLE
[Bug]:     return typeof possibleEnumValue === "undefined" ? Result.err(new UnknownEnumValueError(casted, this.enumKeys, this.enumMapping)) : Result.ok(possibleEnumValue);

### ISSUE THREAD

**Issue by EatDev** [ppauel/typescript-discord-bot#11]
### What happened?

A bug happened! 

![image](https://github.com/ppauel/typescript-discord-bot/assets/71934318/911fd479-c0f3-441a-9d3f-779cf3078ab4)

### Version

newst

**Comment by bowenjw** [comment]
Looks like you have multiple items with the same name in one of the collections.

Also it could be an issue with an object in your code. It is hard for me to say as I have never had this error

**Comment by Yareaj** [comment]
This issue is caused by #10 I'll do a pull request to solve this
